---
environment_name: 'test'
server: 'staging-18535'
cloud_hosting: 'prod.hosting.acquia.com'
git_branch: 'staging'
deploy_type: 'branch'
origin_environment: ''
sync_files_with_origin: false
sync_db_with_origin: false
sync_code: true
url: 'ymcaseattlestg.prod.acquia-sites.com'
domains:
  - 'ymcaseattlestg.prod.acquia-sites.com'
  - 'stg.seattleymca.org'
modules:
  - { name: 'dblog', status: true }
  - { name: 'devel', status: true }
  - { name: 'views_ui', status: true }
  - { name: 'shield', status: true }
  - { name: 'stage_file_proxy', status: false }
pre_drush_commands:
  - { name: 'disable-syncers', status: true, arguments: "" }
  - { name: 'config-set', status: true, arguments: "shield.settings user {{ http_user }} -y" }
  - { name: 'config-set', status: true, arguments: "shield.settings pass {{ http_pass }} -y" }
  - { name: 'config-set', status: true, arguments: "google_tag.settings container_id '' -y" }
post_drush_commands:
  - { name: 'status', status: true, arguments: "" }
  - { name: 'cr', status: true, arguments: "" }
  - { name: 'updb', status: true, arguments: "" }
  - { name: 'entup', status: true, arguments: "" }
  - { name: 'cr', status: true, arguments: "" }
  - { name: 'enable-syncers', status: true, arguments: "" }
cluster: []
