<?php

/**
 * @file
 * Test content values.
 */

/**
 * Returns branches.
 */
function ygs_test_content_branch() {
  $values = [
    [
      'type' => 'branch',
      'title' => 'Accelerator YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Seattle',
        'postal_code' => '98104',
        'address_line1' => '909 Fourth Ave',
      ],
      'field_latitude' => [
        'value' => '47.6054633',
      ],
      'field_longitude' => [
        'value' => '-122.3327679',
      ],
      'field_phone' => [
        'value' => '206.382.5013',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'Auburn Valley YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Auburn',
        'postal_code' => '98001',
        'address_line1' => '1620 Perimeter Rd SW',
      ],
      'field_latitude' => [
        'value' => '47.2934334',
      ],
      'field_longitude' => [
        'value' => '-122.238700',
      ],
      'field_phone' => [
        'value' => '253.833.2770',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'Bellevue Family YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Bellevue',
        'postal_code' => '98007',
        'address_line1' => '14230 Bel-Red Road',
      ],
      'field_latitude' => [
        'value' => '47.626',
      ],
      'field_longitude' => [
        'value' => '-122.14973',
      ],
      'field_phone' => [
        'value' => '425.746.9900',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'Coal Creek Family YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Newcastle',
        'postal_code' => '98059',
        'address_line1' => '13750 Newcastle Golf Club Rd',
      ],
      'field_latitude' => [
        'value' => '47.541',
      ],
      'field_longitude' => [
        'value' => '-122.156',
      ],
      'field_phone' => [
        'value' => '425.282.1500',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'Dale Turner Family YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Shoreline',
        'postal_code' => '98133',
        'address_line1' => '19290 Aurora Ave N',
      ],
      'field_latitude' => [
        'value' => '47.7692',
      ],
      'field_longitude' => [
        'value' => '-122.3453',
      ],
      'field_phone' => [
        'value' => '206.363.0446',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'Downtown Seattle YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Seattle',
        'postal_code' => '98104',
        'address_line1' => '909 Fourth Ave',
      ],
      'field_latitude' => [
        'value' => '47.6054633',
      ],
      'field_longitude' => [
        'value' => '-122.3327679',
      ],
      'field_phone' => [
        'value' => '206.382.5010',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'Matt Griffin YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Seatac',
        'postal_code' => '98188',
        'address_line1' => '3595 S. 188th St',
      ],
      'field_latitude' => [
        'value' => '47.4337',
      ],
      'field_longitude' => [
        'value' => '-122.2882',
      ],
      'field_phone' => [
        'value' => '206.244.5880',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'Meredith Mathews East Madison YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Seattle',
        'postal_code' => '98122',
        'address_line1' => '1700 23rd Ave',
      ],
      'field_latitude' => [
        'value' => '47.6167815',
      ],
      'field_longitude' => [
        'value' => '-122.3022189',
      ],
      'field_phone' => [
        'value' => '206.322.6969',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'Northshore YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Bothell',
        'postal_code' => '98011',
        'address_line1' => '11811 NE 195th Street',
      ],
      'field_latitude' => [
        'value' => '47.768731',
      ],
      'field_longitude' => [
        'value' => '-122.1824087',
      ],
      'field_phone' => [
        'value' => '425.485.9797',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'Sammamish Community YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Sammamish',
        'postal_code' => '98075',
        'address_line1' => '831 228th Ave SE',
      ],
      'field_latitude' => [
        'value' => '47.6006551',
      ],
      'field_longitude' => [
        'value' => '-122.0388',
      ],
      'field_phone' => [
        'value' => '425.391.4840',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'Snoqualmie Valley YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Snoqualmie',
        'postal_code' => '98065',
        'address_line1' => '35018 SE Ridge Street',
      ],
      'field_latitude' => [
        'value' => '47.5323682',
      ],
      'field_longitude' => [
        'value' => '-121.8731367',
      ],
      'field_phone' => [
        'value' => '425.256.3115',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'University Family YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Seattle',
        'postal_code' => '98105',
        'address_line1' => '5003 12th Ave NE',
      ],
      'field_latitude' => [
        'value' => '47.6652252',
      ],
      'field_longitude' => [
        'value' => '-122.3156',
      ],
      'field_phone' => [
        'value' => '206.524.1400',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
    [
      'type' => 'branch',
      'title' => 'West Seattle & Fauntleroy YMCA',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Seattle',
        'postal_code' => '98126',
        'address_line1' => '4515 36th Ave SW',
      ],
      'field_latitude' => [
        'value' => '47.5625359',
      ],
      'field_longitude' => [
        'value' => '-122.3783',
      ],
      'field_phone' => [
        'value' => '206.935.6000',
      ],
      'field_state' => [
        'value' => 0,
      ],
    ],
  ];

  return $values;
}

/**
 * Returns facilities.
 */
function ygs_test_content_facility() {
  $values = [
    [
      'type' => 'facility',
      'title' => 'Test Facility 1',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Seattle',
        'postal_code' => '00001',
        'address_line1' => '001 Test st.',
      ],
      'field_latitude' => [
        'value' => '47.111',
      ],
      'field_longitude' => [
        'value' => '-122.111',
      ],
      'field_phone' => [
        'value' => '000.000.0001',
      ],
    ],
    [
      'type' => 'facility',
      'title' => 'Test Facility 2',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Seattle',
        'postal_code' => '00002',
        'address_line1' => '002 Test st.',
      ],
      'field_latitude' => [
        'value' => '47.222',
      ],
      'field_longitude' => [
        'value' => '-122.222',
      ],
      'field_phone' => [
        'value' => '000.000.0002',
      ],
    ],
    [
      'type' => 'facility',
      'title' => 'Test Facility 3',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Seattle',
        'postal_code' => '00003',
        'address_line1' => '003 Test st.',
      ],
      'field_latitude' => [
        'value' => '47.333',
      ],
      'field_longitude' => [
        'value' => '-122.333',
      ],
      'field_phone' => [
        'value' => '000.000.0003',
      ],
    ],
    [
      'type' => 'facility',
      'title' => 'Test Facility 4',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Seattle',
        'postal_code' => '00004',
        'address_line1' => '004 Test st.',
      ],
      'field_latitude' => [
        'value' => '47.444',
      ],
      'field_longitude' => [
        'value' => '-122.444',
      ],
      'field_phone' => [
        'value' => '000.000.0004',
      ],
    ],
    [
      'type' => 'facility',
      'title' => 'Test Facility 5',
      'moderation_state' => 'published',
      'field_address' => [
        'country_code' => 'US',
        'administrative_area' => 'WA',
        'locality' => 'Seattle',
        'postal_code' => '00005',
        'address_line1' => '005 Test st.',
      ],
      'field_latitude' => [
        'value' => '47.555',
      ],
      'field_longitude' => [
        'value' => '-122.555',
      ],
      'field_phone' => [
        'value' => '000.000.0005',
      ],
    ],
  ];

  return $values;
}
