<?php

/**
 * @file
 * Image related customizations.
 */

/**
 * Implements hook_preprocess_HOOK() for image_style.
 */
function ygs_image_preprocess_image_style(&$variables) {
  $filemime = \Drupal::service('file.mime_type.guesser')->guess($variables['uri']);
  // Do not use image style URL for SVG images.
  if ($filemime == 'image/svg+xml') {
    $variables['image']['#uri'] = file_create_url($variables['uri']);
  }
}

/**
 * Implements hook_preprocess_HOOK() for image.
 */
function ygs_image_preprocess_image(&$variables) {
  $filemime = \Drupal::service('file.mime_type.guesser')->guess($variables['uri']);
  if ($filemime == 'image/svg+xml') {
    $variables['attributes']['class'][] = 'svg-image';
  }
}
