---
# This playbook installs php

- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  sudo: yes

  vars:
    php_version: 5.6
    php_packages:
      - php{{ php_version }}-cli
      - php{{ php_version }}-curl
      - php{{ php_version }}-gd
      - php{{ php_version }}-intl
      - php{{ php_version }}-mcrypt
      - php{{ php_version }}-memcache
      - php{{ php_version }}-imagick
      - php{{ php_version }}-mysql
      - php{{ php_version }}-xdebug
      - php{{ php_version }}-soap
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-xml
      - php{{ php_version }}-dev
      - libapache2-mod-php{{ php_version }}
      - php-mysql
      - php-curl
      - php-gd
      - php-yaml
      - php-mbstring
      - php-pear
      - php-dev
      - php-soap
      - php-xml
      - php-xdebug
      - php5.6-ldap
    php_use_managed_ini: true
    php_display_errors: On
    php_error_reporting: '-1'
    php_session.save_path: /var/lib/php/session
    php_max_execution_time: '300'
    php_memory_limit: 1024M
    php_post_max_size: 64M
    php_upload_max_filesize: 64M

    php_enable_apc: true
    php_apc_enabled_in_ini: true
    php_apc_cache_by_default: "1"
    php_apc_shm_size: "96M"
    php_apc_stat: "1"
    php_apc_enable_cli: "0"
    cibox_php_pcntl: no

  roles:
    - { role: '../core/facade-php' }
    - { role: '../core/facade-php-pear' }
#    - { role: '../core/facade-php-xhprof' }
    - { role: '../core/cibox-php-pcntl' }

  tasks:
    - name: Download compiled MSSQL PHP library
      sudo: yes
      get_url:
        url: http://ygs.ffwua.com/mssql.so
        dest: /usr/lib/php5/20131226/mssql.so

    - name: Install libsybdb5
      apt:
        name: libsybdb5
        state: present

    - name: Add configuration for MSSQL PHP library
      sudo: yes
      lineinfile:
        dest: '/etc/php/5.6/mods-available/mssql.ini'
        line: 'extension=/usr/lib/php5/20131226/mssql.so'
        create: yes
        state: present

    - name: Enable MSSQL PHP library
      sudo: yes
      shell: "phpenmod mssql"

    - name: Restart Apache
      sudo: yes
      service:
        name: apache2
        state: restarted
