admin_css: true
responsive_image: false
one_pixel: true
blazy:
  loadInvisible: false
  offset: 100
  saveViewportOffsetDelay: 50
_core:
  default_config_hash: jhZLw_5eBDtHoK-VUkLxLS9CbW8Vwfek2MP1Gqw19uk
