definitions:
  user__page:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: -49
  user__logout:
    weight: -48
    menu_name: account
    parent: ''
    expanded: false
    enabled: false
_core:
  default_config_hash: g1DpTn9uD9V8pSQcNqXZCysq9SUBllNEZ1LThFzZwrY
