country:
  default: US
first_day: 0
timezone:
  default: America/Los_Angeles
  user:
    configurable: false
    warn: false
    default: 0
_core:
  default_config_hash: iQjcbFvr1eAsR2LUudT1vdUwCUCFYIZvv3-tqYTvMN4
