features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: themes/custom/ymca_seattle/logo_y.svg
favicon:
  use_default: 1
_core:
  default_config_hash: l4oh45UwoKb_V-ysNt2DQJnlgnIG8d2oJO_P6Re_kWM
