---
- name: Deploy branch to Acquia
  shell: "git push {{ acquia_git_url }} {{ git_branch }}"

# Max execution time: 180*5/60 = 15mins.
- name: Wait for code updates
  shell: "ssh -t {{ project_name }}.{{ environment_name }}@{{ server }}.{{ cloud_hosting }} \"drush @{{ project_name }}.{{ environment_name }} ac-task-list --state=started -l {{ url }} --email={{ acquia_user_email }} --key={{ acquia_user_api_key }}\""
  register: result
  until: result.stdout == ""
  retries: 180
  delay: 5
