---
- name: Clear drush cache
  shell: "ssh -t {{ project_name }}.{{ environment_name }}@{{ server }}.{{ cloud_hosting }} \"drush @{{ project_name }}.{{ environment_name }} cache-clear drush -l {{ url }}\""

- name: Run pre drush commands
  shell: "ssh -t {{ project_name }}.{{ environment_name }}@{{ server }}.{{ cloud_hosting }} \"drush @{{ project_name }}.{{ environment_name }} -y {{ item.name }} {{ item.arguments }} -l {{ url }}\""
  when: item.status == true
  register: pre_drush_output
  with_items: pre_drush_commands

- name: Pre drush commands output
  debug: var=item.stdout
  with_items: pre_drush_output.results
  when: pre_drush_output is defined

- name: Sync database with origin environment
  shell: "ssh -t {{ project_name }}.{{ environment_name }}@{{ server }}.{{ cloud_hosting }} \"drush @{{ project_name }}.{{ environment_name }} ah-db-import ~/backups/latest_{{ origin_environment }}.sql.gz --db={{ project_name }} --drop --force -l {{ url }}\""
  when: origin_environment != "" and sync_db_with_origin

- name: Deploy branch to Acquia
  include: branch_deploy.yml
  when: deploy_type == 'branch' and sync_code

- name: Deploy tag to Acquia
  include: tag_deploy.yml
  when: deploy_type == 'tag' and sync_code

- name: Run post drush commands
  shell: "ssh -t {{ project_name }}.{{ environment_name }}@{{ server }}.{{ cloud_hosting }} \"drush @{{ project_name }}.{{ environment_name }} -y {{ item.name }} {{ item.arguments }} -l {{ url }}\""
  when: item.status == true
  register: post_drush_output
  with_items: post_drush_commands

- name: Post drush commands output
  debug: var=item.stdout
  with_items: post_drush_output.results
  when: post_drush_output is defined

- name: Flush cluster caches
  shell: "ssh -t {{ project_name }}.{{ environment_name }}@{{ item.name }}.{{ cloud_hosting }} \"drush @{{ project_name }}.{{ environment_name }} -l {{ url }} ev '\\Drupal\\Core\\PhpStorage\\PhpStorageFactory::get(\\\"twig\\\")->deleteAll();'\""
  when: cluster is defined and item.status == true
  with_items: cluster

- name: Sync files with origin environment
  shell: "ssh -t {{ project_name }}.{{ environment_name }}@{{ server }}.{{ cloud_hosting }} \"drush @{{ project_name }}.{{ origin_environment }} ac-files-copy {{ environment_name }} --email={{ acquia_user_email }} --key={{ acquia_user_api_key }} -l {{ url }}\""
  when: origin_environment != "" and sync_files_with_origin

- name: Enable modules
  shell: "ssh -t {{ project_name }}.{{ environment_name }}@{{ server }}.{{ cloud_hosting }} \"drush @{{ project_name }}.{{ environment_name }} -y en {{ item.name }} -l {{ url }}\""
  when: item.status == true
  with_items: modules

- name: Clear varnish
  ignore_errors: yes
  shell: "ssh -t {{ project_name }}.{{ environment_name }}@{{ server }}.{{ cloud_hosting }} \"drush @{{ project_name }}.{{ environment_name }} ac-domain-purge {{ item }} --email={{ acquia_user_email }} --key={{ acquia_user_api_key }} || true\""
  with_items: domains
