activenet_client.config:
  type: config_object
  label: 'Activenet sync config'
  mapping:
    is_production:
      type: boolean
      label: 'Is production'
    activenet_page:
      type: text
      label: 'Activenet page'
    dw_offset:
      type: text
      label: 'DataWarehouse query offset'
