<?php

/**
 * @file
 * Contains ygs_branch module hooks.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\ygs_branch\Utility\UpdatesQueueProvisioner;

/**
 * Implements hook_theme().
 */
function ygs_schedules_theme() {
  return [
    'ygs_schedules_main' => [
      'variables' => [
        'title' => '',
        'content' => [],
      ],
    ],
    'ygs_schedules_main_class' => [
      'variables' => [
        'title' => '',
        'content' => [],
      ],
    ],
    'ygs_branch_hours_block' => [
      'variables' => [
        'branch_hours' => [],
      ],
    ],
    'ygs_schedules_alerts_block' => [
      'variables' => [
        'alerts' => [],
      ],
    ],
  ];
}
