---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    environment_name: dev
    config_folder: ../config

  vars_files:
    - "{{ config_folder }}/acquia/settings.yml"

  pre_tasks:
    - name: Include specific variables per environment
      include_vars: "{{ config_folder }}/acquia/environments/{{ environment_name }}.yml"

  roles:
    - { role: ../custom/cibox-acquia-backup }
