---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    environment_name: dev
    config_folder: ../config
    pre_backup: true
    post_backup: true

  vars_files:
    - "{{ config_folder }}/acquia/settings.yml"

  pre_tasks:
    - name: Include specific variables per environment
      include_vars: "{{ config_folder }}/acquia/environments/{{ environment_name }}.yml"

  roles:
    # Backup before release.
    - { role: ../custom/cibox-acquia-backup, when: pre_backup }
    # Deployment.
    - { role: ../custom/cibox-acquia-deploy }
    # Backup after release.
    - { role: ../custom/cibox-acquia-backup, when: post_backup }
