<?php

/**
 * @file
 * Contains ygs_article_pager.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ygs_article_pager_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ygs_article_pager module.
    case 'help.page.ygs_article_pager':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a pager block for articles, so that users can easily browser from one to another.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ygs_article_pager_theme() {
  $theme = [];

  $theme['blog_pager_items'] = [
    'template' => 'blog-pager-items',
    'variables' => [
      'previous' => NULL,
      'next' => NULL,
    ],
  ];

  return $theme;
}
